version: "3.7"
services:
  front-envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - hellonet
    expose:
      - "80"
      - "8001"
    ports:
      - "1234:80"
      - "8001:8001"

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    networks:
      hellonet:
        aliases:
          - httpd
    expose:
      - "80"
  id_server:
    build:
      context: ./id-server
      dockerfile: Dockerfile
    networks:
      hellonet:
        aliases:
          - id_server
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
networks:
  hellonet: {}
